services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /srv/docker/volumes/remote-falcon/mongo/db:/data/db #Update the path before the : to a valid path on your machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - traefik-net
  plugins-api:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-plugins-api.git
      args:
        - OTEL_OPTS=
    restart: always
    environment:
      - server.port=8083
      - spring.data.mongodb.uri=mongodb://root:root@mongo:27017/remote-falcon?authSource=admin
      - server.servlet.context-path=/remote-falcon-plugins-api
    networks:
      - traefik-net
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remote-falcon-plugin-api.rule=Host(`docker02.home.kb9kld.org`) && PathPrefix(`/remote-falcon-plugins-api`)"
      - "traefik.http.routers.remote-falcon-plugin-api.priority=10"
      - "traefik.http.services.remote-falcon-plugin-api.loadbalancer.server.port=8083"
  control-panel:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-control-panel.git
      args:
        - OTEL_OPTS=
    restart: always
    environment:
      - server.port=8081
      - web.url=http://docker02.home.kb9kld.org
      - auto-validate-email=true
      - jwt.user=437963
      - spring.data.mongodb.uri=mongodb://root:root@mongo:27017/remote-falcon?authSource=admin
      - github.pat=
      - sendgrid.key=
      - client.header=CF-Connecting-IP
    networks:
      - traefik-net
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remote-falcon-control-panel.rule=Host(`docker02.home.kb9kld.org`) && PathPrefix(`/remote-falcon-control-panel`)"
      - "traefik.http.routers.remote-falcon-control-panel.priority=15"
      - "traefik.http.services.remote-falcon-control-panel.loadbalancer.server.port=8081"
      
  viewer:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-viewer.git
      args:
        - OTEL_OPTS=
    restart: always
    environment:
      - server.port=8082
      - jwt.viewer=437963
      - spring.data.mongodb.uri=mongodb://root:root@mongo:27017/remote-falcon?authSource=admin
      - client.header=CF-Connecting-IP
    networks:
      - traefik-net
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remote-falcon-viewer.rule=Host(`docker02.home.kb9kld.org`) && PathPrefix(`/remote-falcon-viewer`)"
      - "traefik.http.routers.remote-falcon-viewer.priority=10"
      - "traefik.http.services.remote-falcon-viewer.loadbalancer.server.port=8082"
  ui:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-ui.git
      args:
        - HOST_ENV=local
        - VERSION=local
        - CONTROL_PANEL_API=http://docker02.home.kb9kld.org/remote-falcon-control-panel
        - VIEWER_API=http://docker02.home.kb9kld.org/remote-falcon-viewer
        - VIEWER_JWT_KEY=437963
        - GOOGLE_MAPS_KEY=
        - PUBLIC_POSTHOG_KEY=
        - GA_TRACKING_ID=1
        - HOSTNAME_PARTS=4
    restart: always
    depends_on:
      - control-panel
      - viewer
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remote-falcon-ui.rule=Host(`docker02.home.kb9kld.org`) || Host(`lightshow.docker02.home.kb9kld.org`)"
      - "traefik.http.routers.remote-falcon-ui.priority=1"
      - "traefik.http.services.remote-falcon-ui.loadbalancer.server.port=3000"

networks:
  traefik-net:
    external: true