services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /srv/docker/volumes/remote-falcon/mongo/db:/data/db #Update the path before the : to a valid path on your machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - traefik-net
  plugins-api:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-plugins-api.git
      args:
        - OTEL_OPTS=
    restart: always
    environment:
      - spring.data.mongodb.uri=mongodb://root:root@mongo:27017/remote-falcon?authSource=admin
      - server.servlet.context-path=/remote-falcon-plugins-api
    networks:
      - traefik-net
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remote-falcon-plugin-api.rule=Host(`${HOSTNAME}`) && PathPrefix(`/remote-falcon-plugins-api`)"
  control-panel:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-control-panel.git
      args:
        - OTEL_OPTS=
    restart: always
    environment:
      - web.url=http://${HOSTNAME}
      - auto-validate-email=true
      - jwt.user=437963
      - spring.data.mongodb.uri=mongodb://root:root@mongo:27017/remote-falcon?authSource=admin
      - github.pat=
      - sendgrid.key=
      - client.header=CF-Connecting-IP
    networks:
      - traefik-net
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remote-falcon-control-panel.rule=Host(`${HOSTNAME}`) && PathPrefix(`/remote-falcon-control-panel`)"
      
  viewer:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-viewer.git
      args:
        - OTEL_OPTS=
    restart: always
    environment:
      - jwt.viewer=437963
      - spring.data.mongodb.uri=mongodb://root:root@mongo:27017/remote-falcon?authSource=admin
      - client.header=CF-Connecting-IP
    networks:
      - traefik-net
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remote-falcon-viewer.rule=Host(`${HOSTNAME}`) && PathPrefix(`/remote-falcon-viewer`)"
  ui:
    build:
      context: https://github.com/Remote-Falcon/remote-falcon-ui.git
      args:
        - HOST_ENV=local
        - VERSION=local
        - CONTROL_PANEL_API=http://${HOSTNAME}/remote-falcon-control-panel
        - VIEWER_API=http://${HOSTNAME}/remote-falcon-viewer
        - VIEWER_JWT_KEY=437963
        - GOOGLE_MAPS_KEY=
        - PUBLIC_POSTHOG_KEY=
        - GA_TRACKING_ID=${GA_TRACKING_ID}
        - HOSTNAME_PARTS=${HOSTNAME_PARTS}
    restart: always
    depends_on:
      - control-panel
      - viewer
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remote-falcon-ui.rule=Host(`${HOSTNAME}`) || Host(`${VIEWER_HOSTNAME}`)"
      - "traefik.http.routers.remote-falcon-ui.priority=65"

networks:
  traefik-net:
    external: true