name: Build and Publish Image to GitHub Container Registry

on:
  # trigger manual
  workflow_dispatch:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  HOSTNAME: ${{ secrets.HOSTNAME }}
  WEB_URL: "https://${{ secrets.HOSTNAME }}"
  HOSTNAME_PARTS: ${{ secrets.HOSTNAME_PARTS }}
  CONTROL_HOST: ${{ secrets.CONTROL_HOST }}
  VIEWER_HOST: ${{ secrets.VIEWER_HOST }}
  GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
  JWT_VIEWER: ${{ secrets.JWT_KEY }}
      
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    
    steps:
      - name: Set current date as VERSION environment variable
        run: echo "VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v7

      - name: Checkout Remote Falcon
        uses: actions/checkout@v7
        with:
          repository: 'Remote-Falcon/remote-falcon-platform'
          path: 'remote-falcon-platform' # Saves into a local subfolder

      - name: Build all of the services
        run: |
          docker compose build

      - name: Push Docker images for plugins-api
        run: |
          docker compose push plugins-api
          docker tag ghcr.io/jeffu231/rf-plugins-api:latest ghcr.io/jeffu231/rf-plugins-api:$VERSION
          docker push ghcr.io/jeffu231/rf-plugins-api:$VERSION

      - name: Push Docker images for control-panel
        run: |
          docker compose push control-panel
          docker tag ghcr.io/jeffu231/rf-control-panel:latest ghcr.io/jeffu231/rf-control-panel:$VERSION
          docker push ghcr.io/jeffu231/rf-control-panel:$VERSION

      - name: Push Docker images for viewer
        run: |
          docker compose build viewer
          docker compose push viewer
          docker tag ghcr.io/jeffu231/rf-viewer:latest ghcr.io/jeffu231/rf-viewer:$VERSION
          docker push ghcr.io/jeffu231/rf-viewer:$VERSION
      
      - name: Push Docker images for ui
        run: |
          docker compose push ui
          docker tag ghcr.io/jeffu231/rf-ui:latest ghcr.io/jeffu231/rf-ui:$VERSION
          docker push ghcr.io/jeffu231/rf-ui:$VERSION
